---
- name: Configure Frigate NVR with Docker Compose
  hosts: ocean
  become: true
  gather_facts: true

  vars_files:
    - ../../../../vault/secrets.yaml

  vars:
    service: frigate
    image: ghcr.io/blakeblackshear/frigate
    version: stable
    port_ext: 5000
    rtmp_port: 1935
    rtsp_port: 8554
    webrtc_port: 8555
    data: /data01
    files: ../../../../files/frigate
    home: "{{ data }}/services/{{ service }}"
    user: media
    uid: 1001
    gid: 1001

  tasks:

  - name: Ensure base directory exists
    ansible.builtin.file:
      path: "{{ home }}"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0755'

  - name: Ensure subdirectories exist
    ansible.builtin.file:
      path: "{{ home }}/{{ item }}"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0755'
    with_items:
    - config
    - media
    - database

  - name: Create Frigate config file
    ansible.builtin.template:
      src: "{{ files }}/frigate.yml.j2"
      dest: "{{ home }}/config/config.yml"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
    notify:
    - Restart frigate service

  - name: Create docker-compose.yml
    ansible.builtin.template:
      src: "{{ files }}/docker-compose.yml.j2"
      dest: "{{ home }}/docker-compose.yml"
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0644'
    notify:
    - Reload systemd daemon
    - Restart frigate service

  - name: Create frigate systemd service
    ansible.builtin.template:
      src: "{{ files }}/frigate.service.j2"
      dest: "/etc/systemd/system/frigate.service"
      mode: '0644'
    notify:
    - Reload systemd daemon
    - Restart frigate service

  - name: Enable frigate service
    ansible.builtin.systemd:
      name: frigate.service
      enabled: yes
      daemon_reload: yes

  - name: Start frigate service
    ansible.builtin.systemd:
      name: frigate.service
      state: started

  handlers:
  - name: Reload systemd daemon
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Restart frigate service
    ansible.builtin.systemd:
      name: frigate.service
      state: restarted
