---
- name: Configure systemd service for nzbget
  hosts: ocean
  become: true
  vars:
    service: nzbget
    image: linuxserver/nzbget
    version: latest
    nzbget_port: 8901
    exporter_service: nzbget-exporter
    exporter_image: frebib/nzbget-exporter
    exporter_version: latest
    exporter_port: 9452
    data: /data01
    files: ../../../../files/ocean-nzbget
    incoming: "{{ data }}/incoming"
    complete: "{{ data }}/complete"
    home: "{{ data }}/services/{{ service }}"
    user: media

  tasks:

  - name: Ensure basedir exists
    ansible.builtin.file:
      path: "{{ home }}"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0755'

  - name: Ensure directory exists with correct ownership and permissions
    ansible.builtin.file:
      path: "{{ home }}/{{ item }}"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0755'
    with_items:
    - config
    - scratch
    - scripts

  - name: Clone GetScripts repository
    ansible.builtin.git:
      repo: https://github.com/clinton-hall/GetScripts.git
      dest: "{{ home }}/scripts/GetScripts"
      version: master
      update: yes
      force: yes
    notify:
    - Reload nzbget systemd daemon
    - Restart nzbget service

  - name: Clone VideoSort repository
    ansible.builtin.git:
      repo: https://github.com/nzbget/VideoSort.git
      dest: "{{ home }}/scripts/VideoSort"
      version: master
      update: yes
      force: yes
    notify:
    - Reload nzbget systemd daemon
    - Restart nzbget service

  - name: Recursively set ownership on scripts/
    ansible.builtin.file:
      path: "{{ home }}/scripts/"
      state: directory
      recurse: yes

  - name: Create config files
    ansible.builtin.template:
      src: "{{ files }}/config/nzbget.conf.j2"
      dest: "{{ home }}/config/nzbget.conf"
      mode: '0644'
    notify:
    - Reload nzbget systemd daemon
    - Restart nzbget service

  - name: Create nzbget systemd service
    ansible.builtin.template:
      src: "{{ files }}/{{ item }}.j2"
      dest: "/etc/systemd/system/{{ item }}"
      mode: '0644'
    with_items:
    - nzbget.service
    notify:
    - Reload nzbget systemd daemon
    - Restart nzbget service

  - name: Create exporter systemd service
    ansible.builtin.template:
      src: "{{ files }}/{{ item }}.j2"
      dest: "/etc/systemd/system/{{ item }}"
      mode: '0644'
    with_items:
    - nzbget-exporter.service
    notify:
    - Reload exporter systemd daemon
    - Restart exporter service

  handlers:
  - name: Reload nzbget systemd daemon
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Restart nzbget service
    ansible.builtin.systemd:
      name: nzbget.service
      state: restarted

  - name: Reload exporter systemd daemon
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Restart exporter service
    ansible.builtin.systemd:
      name: nzbget-exporter.service
      state: restarted
