---
- name: Configure systemd service for prowlarr
  hosts: ocean
  become: true
  vars:
    service: prowlarr
    image: lscr.io/linuxserver/prowlarr
    version: latest
    prowlarr_port: 9696
    exporter_service: prowlarr-exporter
    exporter_image: ghcr.io/onedr0p/exportarr
    exporter_version: latest
    exporter_port: 9710
    data: /data01
    files: ../../../../files/ocean-prowlarr
    incoming: "{{ data }}/incoming"
    complete: "{{ data }}/complete"
    home: "{{ data }}/services/{{ service }}"
    user: media

  tasks:

  - name: Ensure basedir exists
    ansible.builtin.file:
      path: "{{ home }}"
      state: directory
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0755'

  - name: Create prowlarr systemd service
    ansible.builtin.template:
      src: "{{ files }}/{{ item }}.j2"
      dest: "/etc/systemd/system/{{ item }}"
      mode: '0644'
    with_items:
    - prowlarr.service
    notify:
    - Reload prowlarr systemd daemon
    - Restart prowlarr service

  - name: Create exporter systemd service
    ansible.builtin.template:
      src: "{{ files }}/{{ item }}.j2"
      dest: "/etc/systemd/system/{{ item }}"
      mode: '0644'
    with_items:
    - prowlarr-exporter.service
    notify:
    - Reload exporter systemd daemon
    - Restart exporter service

  handlers:
  - name: Reload prowlarr systemd daemon
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Restart prowlarr service
    ansible.builtin.systemd:
      name: prowlarr.service
      state: restarted

  - name: Reload exporter systemd daemon
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Restart exporter service
    ansible.builtin.systemd:
      name: prowlarr-exporter.service
      state: restarted
