---
- name: Configure systemd service for radarr
  hosts: ocean
  become: true
  vars_files:
    - ../../../../vars/vars_service_ports.yaml

  vars:
    service: radarr
    image: linuxserver/radarr
    version: latest
    radarr_port: "{{ service_ports.radarr.port }}"
    exporter_service: radarr-exporter
    exporter_image: ghcr.io/onedr0p/exportarr
    exporter_version: latest
    exporter_port: "{{ service_ports.radarr_exporter.port }}"
    data: /data01
    files: ../../../../files/ocean-radarr
    incoming: "{{ data }}/incoming"
    complete: "{{ data }}/complete"
    home: "{{ data }}/services/{{ service }}"
    user: media

  tasks:

    - name: Ensure basedir exists
      ansible.builtin.file:
        path: "{{ home }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'

    - name: Create config files
      ansible.builtin.template:
        src: "{{ files }}/config.xml.j2"
        dest: "{{ home }}/config.xml"
        mode: '0644'
      notify:
        - Reload radarr systemd daemon
        - Restart radarr service

    - name: Create radarr systemd service 
      ansible.builtin.template:
        src: "{{ files }}/{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        mode: '0644'
      with_items:
      - radarr.service
      notify:
        - Reload radarr systemd daemon
        - Restart radarr service

    - name: Create exporter systemd service 
      ansible.builtin.template:
        src: "{{ files }}/{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        mode: '0644'
      with_items:
      - radarr-exporter.service
      notify:
        - Reload exporter systemd daemon
        - Restart exporter service

  handlers:
    - name: Reload radarr systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart radarr service
      ansible.builtin.systemd:
        name: radarr.service
        state: restarted

    - name: Reload exporter systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart exporter service
      ansible.builtin.systemd:
        name: radarr-exporter.service
        state: restarted
        enabled: true
