---
- name: Configure systemd service for sonarr
  hosts: ocean
  become: true
  vars:
    service: sonarr
    image: linuxserver/sonarr
    version: latest
    sonarr_port: 8902
    exporter_service: sonarr-exporter
    exporter_image: ghcr.io/onedr0p/exportarr
    exporter_version: latest
    exporter_port: 9708
    data: /data01
    files: ../../../../files/ocean-sonarr
    incoming: "{{ data }}/incoming"
    complete: "{{ data }}/complete"
    home: "{{ data }}/services/{{ service }}"
    user: media

  tasks:

    - name: Ensure basedir exists
      ansible.builtin.file:
        path: "{{ home }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'

    - name: Create config files
      ansible.builtin.template:
        src: "{{ files }}/config.xml.j2"
        dest: "{{ home }}/config.xml"
        mode: '0644'
      notify:
        - Reload sonarr systemd daemon
        - Restart sonarr service

    - name: Create sonarr systemd service 
      ansible.builtin.template:
        src: "{{ files }}/{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        mode: '0644'
      with_items:
      - sonarr.service
      notify:
        - Reload sonarr systemd daemon
        - Restart sonarr service

    - name: Create exporter systemd service 
      ansible.builtin.template:
        src: "{{ files }}/{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        mode: '0644'
      with_items:
      - sonarr-exporter.service
      notify:
        - Reload exporter systemd daemon
        - Restart exporter service

  handlers:
    - name: Reload sonarr systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart sonarr service
      ansible.builtin.systemd:
        name: sonarr.service
        state: restarted

    - name: Reload exporter systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart exporter service
      ansible.builtin.systemd:
        name: sonarr-exporter.service
        state: restarted
        enabled: true
