---
- name: Deploy DCGM Exporter
  hosts: ocean
  become: true
  vars:
    user: terrac
    home: /home/terrac
    service_name: dcgm-exporter

  tasks:
    - name: Create dcgm-exporter directory
      file:
        path: "{{ home }}/{{ service_name }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'

    - name: Copy docker-compose template
      template:
        src: "../../../../files/ocean-nvidia/docker-compose.yml.j2"
        dest: "{{ home }}/{{ service_name }}/docker-compose.yml"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'
      notify: Restart dcgm-exporter

    - name: Copy systemd service file
      template:
        src: "../../../../files/ocean-nvidia/dcgm-exporter.service.j2"
        dest: "/etc/systemd/system/{{ service_name }}.service"
        owner: root
        group: root
        mode: '0644'
      notify: Restart dcgm-exporter

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Restart dcgm-exporter
      systemd:
        name: "{{ service_name }}"
        state: restarted
        enabled: yes
        daemon_reload: yes
